//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFX.Extended.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FinancialCalculatorCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinancialCalculatorCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftFX.Extended.Tests.Resources.FinancialCalculatorCases", typeof(FinancialCalculatorCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;USDCHF&quot;; From = &quot;CHF&quot;; To = &quot;USD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Account: Tag = &quot;3&quot;; Type = Gross(1); Leverage = 100(0x0000000000005940); Balance = 100000(0x00000000006AF840); Currency = &quot;USD&quot;; Profit = 0(0x0000000000000000); Pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_000 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NOKSEK&quot;; From = &quot;SEK&quot;; To = &quot;NOK&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 1(0x000000000000F03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;USDNOK&quot;; From = &quot;NOK&quot;; To = &quot;USD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 1(0x000000000000F03F); MarginFactorOfPositions = 1(0x00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_001 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;CADJPY&quot;; From = &quot;JPY&quot;; To = &quot;CAD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;SGDJPY&quot;; From = &quot;JPY&quot;; To = &quot;SGD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_002 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;AUDNZD&quot;; From = &quot;NZD&quot;; To = &quot;AUD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NZDSGD&quot;; From = &quot;SGD&quot;; To = &quot;NZD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_003 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NZDSGD&quot;; From = &quot;SGD&quot;; To = &quot;NZD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 1(0x000000000000F03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NZDUSD&quot;; From = &quot;USD&quot;; To = &quot;NZD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 1(0x000000000000F03F); MarginFactorOfPositions = 1(0x00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_004 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Currency: &quot;USD&quot;; 
        ///Currency: &quot;EUR&quot;; 
        ///Currency: &quot;GBP&quot;; 
        ///Currency: &quot;CHF&quot;; 
        ///Currency: &quot;JPY&quot;; 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;GBPSGD&quot;; From = &quot;SGD&quot;; To = &quot;GBP&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;GBPUSD&quot;; From = &quot;USD&quot;; To = &quot;GBP&quot;; Contra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_005 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NZDUSD&quot;; From = &quot;USD&quot;; To = &quot;NZD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;XAUUSD&quot;; From = &quot;USD&quot;; To = &quot;XAU&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_006 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NZDUSD&quot;; From = &quot;USD&quot;; To = &quot;NZD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;XAGUSD&quot;; From = &quot;USD&quot;; To = &quot;XAG&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_007 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NZDCHF&quot;; From = &quot;CHF&quot;; To = &quot;NZD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NZDUSD&quot;; From = &quot;USD&quot;; To = &quot;NZD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_008 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NOKSEK&quot;; From = &quot;SEK&quot;; To = &quot;NOK&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Price: Symbol = &quot;USDNOK&quot;; Bid = 6.1(0x6666666666661840); Ask = 6.2(0xCDCCCCCCCCCC1840); 
        ///Price: Symbol = &quot;USDRUB&quot;; Bid = 35(0x0000000000804140); Ask = 36(0x0000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_009 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;GBPSGD&quot;; From = &quot;SGD&quot;; To = &quot;GBP&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;GBPUSD&quot;; From = &quot;USD&quot;; To = &quot;GBP&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_010 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;EURUSD&quot;; From = &quot;USD&quot;; To = &quot;EUR&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Price: Symbol = &quot;EURUSD&quot;; Bid = 1.35(0x9A9999999999F53F); Ask = 1.36(0xC3F5285C8FC2F53F); 
        ///Account: Tag = &quot;1&quot;; Type = Gross(1); Leverage = 100(0x0000000000005940); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_011 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;NOKSEK&quot;; From = &quot;SEK&quot;; To = &quot;NOK&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 1(0x000000000000F03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;USDNOK&quot;; From = &quot;NOK&quot;; To = &quot;USD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 1(0x000000000000F03F); MarginFactorOfPositions = 1(0x00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_012 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;GBPSGD&quot;; From = &quot;SGD&quot;; To = &quot;GBP&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;GBPUSD&quot;; From = &quot;USD&quot;; To = &quot;GBP&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_014 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;EURUSD&quot;; From = &quot;USD&quot;; To = &quot;EUR&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Price: Symbol = &quot;EURUSD&quot;; Bid = 1.35(0x9A9999999999F53F); Ask = 1.36(0xC3F5285C8FC2F53F); 
        ///Account: Tag = &quot;3&quot;; Type = Gross(1); Leverage = 100(0x0000000000005940); [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_015 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;CHFJPY&quot;; From = &quot;JPY&quot;; To = &quot;CHF&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;USDCHF&quot;; From = &quot;CHF&quot;; To = &quot;USD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_016 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator: Version = &quot;Initial&quot;; MarginMode = Dynamic(0); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;CHFJPY&quot;; From = &quot;JPY&quot;; To = &quot;CHF&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1(0x000000000000F03F); MarginFactorOfLimitOrders = 1(0x000000000000F03F); MarginFactorOfStopOrders = 1(0x000000000000F03F); 
        ///Symbol: Tag = &quot;&quot;; Symbol = &quot;USDCHF&quot;; From = &quot;CHF&quot;; To = &quot;USD&quot;; ContractSize = 1(0x000000000000F03F); Hedging = 0.5(0x000000000000E03F); MarginFactorOfPositions = 1( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinancialCalculator_Case_018 {
            get {
                return ResourceManager.GetString("FinancialCalculator_Case_018", resourceCulture);
            }
        }
    }
}
