// <auto-generated />
namespace Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5));
        
        string IMigrationMetadata.Id
        {
            get { return "201301241020102_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
