// <auto-generated />
namespace Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_7));
        
        string IMigrationMetadata.Id
        {
            get { return "201302061018097_7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
